//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int addressId { get; set; }
        public Nullable<int> custId { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
