//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.Carts = new HashSet<Cart>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int artId { get; set; }
        public int artistId { get; set; }
        public string artName { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string description { get; set; }
        public string material { get; set; }
        public string medium { get; set; }
        public string style { get; set; }
        public string picture { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> isDelete { get; set; }
    
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
